name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./unit-test # Specify the working directory

      - name: Run tests
        run: npm test
        working-directory: ./unit-test # Specify the working directory
